// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_app.tsx";
import * as $1 from "./routes/api/contact.ts";
import * as $2 from "./routes/api/count.ts";
import * as $3 from "./routes/api/test-contact.ts";
import * as $4 from "./routes/index.tsx";
import * as $$0 from "./islands/Contact.tsx";
import * as $$1 from "./islands/Counter.tsx";
import * as $$2 from "./islands/Intro.tsx";

const manifest = {
  routes: {
    "./routes/_app.tsx": $0,
    "./routes/api/contact.ts": $1,
    "./routes/api/count.ts": $2,
    "./routes/api/test-contact.ts": $3,
    "./routes/index.tsx": $4,
  },
  islands: {
    "./islands/Contact.tsx": $$0,
    "./islands/Counter.tsx": $$1,
    "./islands/Intro.tsx": $$2,
  },
  baseUrl: import.meta.url,
};

export default manifest;
