// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_app.tsx";
import * as $1 from "./routes/api/contact.ts";
import * as $2 from "./routes/index.tsx";
import * as $$0 from "./islands/Contact.tsx";
import * as $$1 from "./islands/Intro.tsx";

const manifest = {
  routes: {
    "./routes/_app.tsx": $0,
    "./routes/api/contact.ts": $1,
    "./routes/index.tsx": $2,
  },
  islands: {
    "./islands/Contact.tsx": $$0,
    "./islands/Intro.tsx": $$1,
  },
  baseUrl: import.meta.url,
};

export default manifest;
